---
- name: Installation, Docker Flask and Docker Nginx
  hosts: all
  become: yes

  tasks:
    - name: "Apt-get update"
      apt:
        update_cache: yes
        cache_valid_time: 360
    - name: Install Docker
      apt:
        name:
        - "docker.io"
        - "python3-pip"
        state: present
    - name: Install Docker SDK for Python
      pip:
       name: docker
       executable: pip3
    - name: Create Directory for projects
      file: path=/opt/docker state=directory
    - name: Copy NGINX docker 
      copy:
        src: nginx
        dest: /opt/docker 
        mode: 0755
        owner: root
        group: root
    - name: Build Nginx Docker container 
      community.docker.docker_image:
        build: 
          path: /opt/docker/nginx
        name: nginx
        tag: v2
        source: build
    - name: Copy Flask docker 
      copy:
        src: flask-site
        dest: /opt/docker 
        mode: 0755
        owner: root
        group: root
    - name: Build Flask Docker container 
      community.docker.docker_image:
        build: 
          path: /opt/docker/flask-site
        name: flask
        tag: v1
        source: build 
    - name: Create a network
      community.docker.docker_network:
        name: flask
    - name: Run Flask 1
      docker_container:
         name: flask1
         image: flask:v1 
         state: started
         exposed_ports: 5000
         networks:
           - name: flask
    - name: Run Flask 2
      docker_container:
         name: flask2
         image: flask:v1 
         state: started
         exposed_ports: 5000
         networks:
           - name: flask
    - name: Run Nginx
      docker_container:
         name: nginx
         image: nginx:v2 
         state: started
         published_ports: "80:80"
         exposed_ports: 80
         networks:
           - name: flask